services:
  server:
    image: anietog1/prediccion-ventas:latest
    restart: always
    environment:
      - DATABASE_SOURCE=s3://predecir-ventas-data/02-trusted/bdCompletarAgrupRefinada.csv
    ports:
      - 80:80
